### ISSUE TITLE
导入运行就报错了

### ISSUE THREAD

**Issue by Lou0083** [CreditTone/mitmproxy-java#4]
导入运行就报错了
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at com.deep007.mitmproxyjava.grpc.MitmProxyHubServerGrpc$MitmProxyHubServerBlockingStub.start(MitmProxyHubServerGrpc.java:223)
	at com.deep007.mitmproxyjava.mitmproxy.RemoteMitmproxy.start(RemoteMitmproxy.java:104)
	at com.deep007.mitmproxyjava.mitmproxy.RemoteMitmproxy.main(RemoteMitmproxy.java:182)
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:8899
Caused by: java.net.ConnectException: Connection refused: no further information

**Comment by zhouhuahu123** [comment]
![image](https://user-images.githubusercontent.com/39817618/181933494-229257ad-da39-460a-9a50-901b255f602e.png)
This is my configuration. After starting port 60051, execute the code to send the same error! Is there any solution?
